@baseUrl = http://localhost:3333

# @name create_restaurant
POST {{baseUrl}}/restaurants
Content-Type: application/json

{
    "restaurantName": "Restaurant Name",
    "managerName": "Manager Name",
    "managerEmail": "manager@manager.com",
    "managerPhone": "339999999",
   "restaurantDescription": "Restaurant Description"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json


{
    "email": "admin@admin.com"
}


###

# @name profile
GET {{baseUrl}}/me
Cookie: auth=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvbXAxbHRqYjhoOWJucnVocTRrN2F5bHciLCJyZXN0YXVyYW50SWQiOiJvNmoya2Qwcm92NGRqMXRta3c5amV3d2kifQ.lYILwR_1p1Q9XMu7l5w0pjGr8In2ZoBOWttYzy3RJq0



